version: '2.0'

services:
  nginx:
    restart: always
    image: nginx:1.18.0-alpine
    ports:
      - 8080:80
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /usr/share/caddy:/var/www/html
      - /root/.acme.sh:/root/.acme.sh